---
abstract: 'An interface to a Riak server.'
author:
  - 'Andrew Nelson <anelson at cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::Memory::Cycle: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Riak
requires:
  Digest::MD5: 0
  HTTP::Headers: 0
  HTTP::Headers::ActionPack: 0
  HTTP::Headers::ActionPack::LinkHeader: 0
  HTTP::Headers::ActionPack::LinkList: 0
  HTTP::Request: 0
  HTTP::Response: 0
  JSON::XS: 0
  LWP: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  Sub::Exporter: 0
  Test::More: 0
  Try::Tiny: 0
  URI: 0
  URL::Encode: 0
  overload: 0
  strict: 0
  warnings: 0
resources:
  repository: http://github.com/holophrastic/data-riak.git
version: 1.0
